### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by soikmd2** [martellaj/shortfuts#68] opened 2018-04-02 04:23 UTC
Hey buddy. As we can see, you are updating the extension.

I am not getting to activate and use it. Already set a few shortcuts, but they don`t work, tried toggling on/off, but had no success.

![image](https://user-images.githubusercontent.com/883969/38183150-6e014ddc-3614-11e8-8739-1dd625bf817c.png)

**Comment by martellaj** [comment] 2018-04-02 04:27
Can you open the dev tools and see what errors are being displayed? I'm not having any issues.

On mobile, so please excuse any errors or brevity.
________________________________

**Comment by martellaj** [comment] 2018-04-02 04:48
I verified on my MacBook and on my Surface Laptop, so I can confirm it works on both OSes. I'll need more information from you before any further investigation. Some helpful things can include:

- Details on what shortcuts are failing and where in the app you're trying to activate it
- Error logs from the Chrome dev console (you can filter by using [shortfuts])

**Comment by soikmd2** [comment] 2018-04-02 05:00
Nvm. It`s working.

I am using Chrome and Windows 10. Just needed to restart Chrome to get the extension working again.

Btw... with this native chrome shortcuts we can only pick CTRL or ALT + letters as shortcuts. What about any alpha numeric key, is it still possible?

**Comment by martellaj** [comment] 2018-04-02 05:06
Unfortunately not. It was a tradeoff I made because I've had far more people ask about customizing keybindings or turning off certain shortcuts. With native Chrome hotkeys, both of these asks can be accomplished.

I thought using the modifier key would be a little clumsy, but it only takes a little getting used to and it's all good. If there's so much blowback with the added functionality, I'll consider adding in a "legacy" mode where it behaved like v2 (hard-coded shortcuts that the user can't control) and letting users have a choice. A feature like that would be extra overhead and really won't be considered unless there's a lot of complaints (or a large donation).

Closing the issue since the extension is working just fine, but feel free to continue the discussion!

**Closed by martellaj** 2018-04-02 05:06 UTC
