### ISSUE TITLE
Add one shortcut for "Search" and one shortcut for "Modify search"

### ISSUE THREAD

**Issue by andreiiulian90** [martellaj/shortfuts#40] opened 2017-10-25 13:09 UTC
This should work in "Search the transfer market" menu and the second one in "Search results" menu.
Thanks.

**Comment by martellaj** [comment] 2017-10-25 14:51
Yes, I'm already tracking an issue to make search work on the "Search the Transfer Market" page (#30), but I've had no luck faking click/touch events on buttons in the main part of the app (i.e. that search button, the "Store All in Club" button, etc.). I saw you forked, so if you can figure it out, that would be *invaluable*.

This issue really covers 2 things. The second bit about "Modify search" is unnecessary - you can already use "backspace" to return to the search form.

Given that your first issue is a dupe of #30 and the second issue is unnecessary, I'm closing this one. If you get "search" working for the other page, please submit a PR referencing #30. 👍

**Closed by martellaj** 2017-10-25 14:51 UTC

**Comment by andreiiulian90** [comment] 2017-10-26 07:18
I'll check in the weekend but I don't have much experience, at least send me a tool that you use so that I can try some scenarios.
